[build]
  command = "npm install && npm --prefix client ci && npm --prefix client run build"
  publish = "client/dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# Single Page App fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
